openapi: 3.2.0
info:
  title: Shipping Addresses API
  description: Shipping Service API which provides integration with shipping services for shipping rates, purchasing labels, and tracking shipments.
  version: 1.3.6+a49f73049e
security:
- Bearer: []
tags:
- name: Addresses
paths:
  /api/v1/addresses:
    post:
      tags:
      - Addresses
      summary: Create Address
      description: Creates a new address and optionally verifies it.
      operationId: CreateAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressModel'
          text/json:
            schema:
              $ref: '#/components/schemas/AddressModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AddressModel'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SavedAddressModel'
            application/json:
              schema:
                $ref: '#/components/schemas/SavedAddressModel'
            text/json:
              schema:
                $ref: '#/components/schemas/SavedAddressModel'
components:
  schemas:
    SavedAddressModel:
      required:
      - postalCode
      type: object
      properties:
        carrierFacility:
          type:
          - string
          - 'null'
          description: The specific designation for the address (only relevant if the address is a carrier facility).
        city:
          type:
          - string
          - 'null'
          description: The city the address is located in.
        company:
          type:
          - string
          - 'null'
          description: The name of the company.
        country:
          type:
          - string
          - 'null'
          description: The ISO 3166 code of the country the address is located in.
        email:
          type:
          - string
          - 'null'
          description: The email address of the person or organization.
        federalTaxId:
          type:
          - string
          - 'null'
          description: The federal tax ID of the person or organization.
        name:
          type:
          - string
          - 'null'
          description: The name of the person or organization.
        phone:
          type:
          - string
          - 'null'
          description: The phone number of the person or organization.
        residential:
          type:
          - boolean
          - 'null'
          description: Whether the address is a residential address.
        state:
          type:
          - string
          - 'null'
          description: The state the address is located in.
        stateTaxId:
          type:
          - string
          - 'null'
          description: The state tax ID of the person or organization.
        street1:
          type:
          - string
          - 'null'
          description: The first line of the street address.
        street2:
          type:
          - string
          - 'null'
          description: The second line of the street address.
        postalCode:
          minLength: 1
          type: string
          description: The postal code the address is located in.
        verify:
          type:
          - boolean
          - 'null'
          description: Indicates if the address should be requested to be verified or not.
        id:
          type:
          - string
          - 'null'
          description: Address unique ID
        verifications:
          $ref: '#/components/schemas/AddressVerificationResult'
      additionalProperties: false
      description: Represents an address that has been created and optionally verified
    AddressVerificationResult:
      type: object
      properties:
        verifiedPostalCode:
          type:
          - boolean
          - 'null'
          description: Indicates whether the postal code has been verified
        verifiedAddress:
          type:
          - boolean
          - 'null'
          description: Indicates whether the street/city/country has been verified
        postalCodeErrors:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Provides verification errors
        addressErrors:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Provides verification errors
        latitude:
          type:
          - number
          - 'null'
          description: The latitude of the address
          format: float
        longitude:
          type:
          - number
          - 'null'
          description: The longitude of the address
          format: float
        timeZone:
          type:
          - string
          - 'null'
          description: The time zone of the address
      additionalProperties: false
      description: Represents address verification results
    AddressModel:
      required:
      - postalCode
      type: object
      properties:
        carrierFacility:
          type:
          - string
          - 'null'
          description: The specific designation for the address (only relevant if the address is a carrier facility).
        city:
          type:
          - string
          - 'null'
          description: The city the address is located in.
        company:
          type:
          - string
          - 'null'
          description: The name of the company.
        country:
          type:
          - string
          - 'null'
          description: The ISO 3166 code of the country the address is located in.
        email:
          type:
          - string
          - 'null'
          description: The email address of the person or organization.
        federalTaxId:
          type:
          - string
          - 'null'
          description: The federal tax ID of the person or organization.
        name:
          type:
          - string
          - 'null'
          description: The name of the person or organization.
        phone:
          type:
          - string
          - 'null'
          description: The phone number of the person or organization.
        residential:
          type:
          - boolean
          - 'null'
          description: Whether the address is a residential address.
        state:
          type:
          - string
          - 'null'
          description: The state the address is located in.
        stateTaxId:
          type:
          - string
          - 'null'
          description: The state tax ID of the person or organization.
        street1:
          type:
          - string
          - 'null'
          description: The first line of the street address.
        street2:
          type:
          - string
          - 'null'
          description: The second line of the street address.
        postalCode:
          minLength: 1
          type: string
          description: The postal code the address is located in.
        verify:
          type:
          - boolean
          - 'null'
          description: Indicates if the address should be requested to be verified or not.
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: oauth2
      description: OAuth 2.0 Client Credentials Flow with API Users issued from Integration Engine Management Console
      flows:
        clientCredentials:
          tokenUrl: https://api-user.integrations.ecimanufacturing.com/oauth2/api-user/token
          scopes:
            openid: openid
