openapi: 3.2.0
info:
  title: ERP API v2.1 Payment Term API
  description: Provides a common API surface for accessing ECI ERP products.
  contact:
    name: ECI Manufacturing Division Integration Team
    url: https://www.ecisolutions.com/support/
  version: 3.5.585+b1e45fd230
servers:
- url: https://api-erp.integrations.ecimanufacturing.com:443
  description: Production
security:
- Bearer: []
tags:
- name: Payment Term
paths:
  /api/v2.1/payment-terms:
    get:
      tags:
      - Payment Term
      summary: Get a list of PaymentTerm from the ERP system that match the given filters
      description: 'Gets a list of PaymentTerm.


        ## Supported ERPs

        - M1

        - JobBOSS²

        - Macola

        ## Resource Features

        Feature |Supported |Notes

        ------------|------------|------------

        Filter Expressions|**Yes**|

        Sort Expressions|**Yes**

        Field Selection|**Yes**

        Pagination|**Yes**

        UniqueID|uniqueID|

        ## Features by Field

        Field |Filterable |Sortable |Supported ERPs

        ------------|------------|------------|------------

        description|No|Yes|M1, JobBOSS², Macola

        paymentTermID|Yes|Yes|M1, JobBOSS², Macola

        rowVersion|Yes|Yes|M1, JobBOSS², Macola

        uniqueID|Yes|Yes|M1, JobBOSS², Macola'
      parameters:
      - name: fields
        in: query
        description: A comma-separated list of fields to include in the result.
        schema:
          type: string
      - name: sort
        in: query
        description: A comma-separated list of <a href='#sortexpr'>sort expressions</a>.
        schema:
          type: string
      - name: take
        in: query
        description: Limit the number of results being returned
        schema:
          minimum: 0
          type: integer
      - name: skip
        in: query
        description: The number of results to skip. Combine with 'take' to fetch records in pages
        schema:
          minimum: 0
          type: integer
      - name: count
        in: query
        description: '<a href=''#countparam''>Data and count</a> response behavior '
        schema:
          maximum: 2
          minimum: 0
          type: integer
      - name: filters
        in: query
        description: See <a href='#filterexpr'>Filter Expressions</a> for query string syntax. The Test UI and any generated code tool may expose filter parameters as a dictionary of name/value pairs, but if creating a raw HTTP request, they must be provided on the querystring as defined in the Filter Expression section.
        style: form
        schema:
          type: object
          additionalProperties:
            type: string
        examples:
          Empty:
            description: No filters applied
          'Example #1':
            description: A dictionary of name/value pairs that will be serialized as querystring parameters in the format ```name[operator]=value```
            value:
              paymentTermID[eq]: abc123
              rowVersion[gte]: 123
              uniqueID[eq]: cc90686b-399e-4094-b431-fa462f84b0a8
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PaymentTermListResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentTermListResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/PaymentTermListResponse'
      operationId: getApiV21PaymentTerms
      x-operation-id-source: derived
components:
  schemas:
    PaymentTerm:
      title: PaymentTerm
      type: object
      properties:
        description:
          type: string
        paymentTermID:
          type: string
        rowVersion:
          type: integer
          format: int64
        uniqueID:
          type: string
    PaymentTermListResponse:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PaymentTerm'
          readOnly: true
        resultCount:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: oauth2
      description: OAuth 2.0 Client Credentials Flow with API Users issued from Integration Engine Management Console
      flows:
        clientCredentials:
          tokenUrl: https://api-user.integrations.ecimanufacturing.com/oauth2/api-user/token
          scopes:
            openid: openid
