openapi: 3.2.0
info:
  title: JobBOSS² Public Reports API
  description: Provides a common API surface for accessing ECI ERP JobBOSS².
  version: v1
servers:
- url: https://api-jb2.integrations.ecimanufacturing.com:443
  description: API Host
security:
- Bearer: []
tags:
- name: Reports
paths:
  /api/v1/reports:
    post:
      tags:
      - Reports
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        '200':
          description: Success
      summary: Create api reports
      x-summary-source: derived
      operationId: postApiV1Reports
      x-operation-id-source: derived
  /api/v1/reports/{requestId}:
    get:
      tags:
      - Reports
      parameters:
      - name: requestId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
      summary: Get api reports by request id
      x-summary-source: derived
      operationId: getApiV1ReportsByRequestId
      x-operation-id-source: derived
components:
  securitySchemes:
    Bearer:
      type: oauth2
      description: OAuth 2.0 Client Credentials Flow with API Users issued from Integration Engine Management Console
      flows:
        clientCredentials:
          tokenUrl: https://api-user.integrations.ecimanufacturing.com/oauth2/api-user/token
          scopes:
            openid: openid
